apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mongo-pv
  labels:
    type: pv

spec: 
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo
